"""add submission detail

Revision ID: 95136b762943
Revises: ee821ced8334
Create Date: 2026-06-20 22:31:26.324438

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95136b762943"
down_revision: str | None = "ee821ced8334"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("detail", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "detail")
    # ### end Alembic commands ###
