"""add submission sample_only

Revision ID: fc8599d9d77c
Revises: 95136b762943
Create Date: 2026-06-20 22:53:24.696017

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8599d9d77c"
down_revision: str | None = "95136b762943"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("sample_only", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "sample_only")
    # ### end Alembic commands ###
